# Site settings
title: "YewLee Wong's Resume"
description: "Associate Software Engineer at Sitecore Malaysia, Former Data Engineer."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yew Lee, Wong"
resume_title:                   "Associate Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yewlee456@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+(Six Zero)11-5421 8853"
resume_contact_address:         "Kuala Lumpur, Malaysia"

# resume_header_contact_info:     "Kuala Lumpur, Malaysia • ---- • yewlee456@gmail.com"
resume_header_contact_info:     "Kuala Lumpur, Malaysia • +(60)11-5421 (8853) • yewlee456@gmail.com"
display_header_contact_info:    "true"
resume_header_status:           "Open To Work & Research Opportunities."

resume_header_intro: "<p>Currently employed as Associate Software Engineer at Sitecore Malaysia. Former Data Engineer at Handshakes by DC Frontier. Posses operational and technical experience on SAAS product of different Multinational Corporations.  Graduate of Data Science major of Computer Science Bachelor Degree, with strong academic exposure on Data Engineering, Database Technology, Business Intelligence, Machine Learning and Artificial Intelligence. With proven leadership track record and exposure in research throughout academic years. Do possesses high interest in Data Engineering, Data Analytics, Computer Vision & Human Rights.</p>"



# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_publishes:       true
resume_section_associations:    true
resume_section_volunteers:      true    
resume_section_languages:       true
resume_section_interests:       true
# resume_section_links:           true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/wyewlee"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yewlee/"
  resume_instagram_url:         "https://www.instagram.com/wongyewlee/"
  resume_website_url:           "http://www.yewlee.tech"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

#google analytics G-2T25Z0YZTC
google_analytics: "G-2T25Z0YZTC"   

#TODO
#badges of credentials